FROM jrottenberg/ffmpeg:3.3-alpine
FROM node:7.7.1-alpine

COPY --from=0 / /

WORKDIR /usr/src/app

EXPOSE 3001
EXPOSE 4001
CMD [ "yarn", "start" ]

RUN yarn global add typescript node-gyp

COPY package.json /usr/src/app/
COPY google-key.json /usr/src/app/
RUN yarn install

# Bundle app source
COPY ./ /usr/src/app
RUN yarn build